// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 3);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1701868368);
user_pref("app.update.lastUpdateTime.region-update-timer", 1701868368);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1701868368);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1701868398);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1701868368);
user_pref("browser.region.update.updated", 1701868340);
user_pref("browser.search.region", "DE");
user_pref("calendar.caldav.googleResync", 1701868339);
user_pref("calendar.list.sortOrder", "d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430");
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.calendar-main-default", true);
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.calendar-main-in-composite", true);
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.disabled", true);
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.name", "Home");
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.type", "storage");
user_pref("calendar.registry.d4b6868e-cdb7-41e5-a9e0-dd7bd1d2e430.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Berlin");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1701868705);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231128185445");
user_pref("extensions.lastAppVersion", "115.5.1");
user_pref("extensions.lastPlatformVersion", "115.5.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"57119821-18b1-42dd-8ae2-93246a5a9015\",\"google@search.mozilla.org\":\"09480473-f898-4238-bd90-82b8decc8fc2\",\"ddg@search.mozilla.org\":\"75a18a25-4d44-4ff4-b3ca-5ad525b3ba39\",\"amazondotcom@search.mozilla.org\":\"7e4470b3-b3e1-420e-93b3-9021838dc2e9\",\"wikipedia@search.mozilla.org\":\"7004809f-556c-47f3-983b-a051fdc077ab\",\"bing@search.mozilla.org\":\"2eaaa6da-21dc-46ff-a126-5eebe106d910\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1701868543);
user_pref("intl.locale.requested", "en-US,de");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.compose.attachment_reminder_keywords", ".doc,.pdf,.xls,.ppt,.rtf,.pps,attachment,attach,attached,attaching,enclosed,CV,cover letter,Anhang,angehangen");
user_pref("mail.e2ee.auto_enable", true);
user_pref("mail.spam.manualMark", true);
user_pref("mail.tabs.autoHide", false);
user_pref("mail.tabs.drawInTitlebar", false);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "c702cc03-f623-4e4a-86fd-c2c68c5d246");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.5.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("messenger.status.reportIdle", false);
user_pref("network.cookie.cookieBehavior", 2);
user_pref("offline.download.download_messages", 1);
user_pref("offline.startup_state", 4);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1701868543);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -2431);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1701870799);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1701870799);
user_pref("services.settings.thunderbird.search-config.last_check", 1701870799);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1701870799);
user_pref("spellchecker.dictionary", "en-US,de-DE");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1701868543);
user_pref("toolkit.startup.last_success", 1701868704);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20231128185445");
